version: 2.1

orbs:
  composer: itinerisltd/composer@0.2

workflows:
  test:
    jobs:
      - composer/install:
          name: test
          executor: composer/seven
          post-steps:
            - composer/exec:
                command: test
      - composer/install:
          name: test:e2e
          executor: composer/seven
          post-steps:
            - composer/exec:
                command: test:e2e
